# Generated by Django 3.2.6 on 2021-08-31 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryFi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dairy_contents',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
